In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:.2f}'.format

In [4]:
df_dirty = pd.read_csv(r'C:\Users\rashid\Desktop\md_retail_analysis\data\raw\customer_shopping_data.csv')
df = df_dirty.copy()
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon

In [5]:
df.shape

(99457, 10)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  str
 1   customer_id     99457 non-null  str
 2   gender          99457 non-null  str
 3   age             99457 non-null  int64
 4   category        99457 non-null  str
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  str
 8   invoice_date    99457 non-null  str
 9   shopping_mall   99457 non-null  str
dtypes: float64(1), int64(2), str(7)
memory usage: 7.6 MB

In [7]:
df.describe()

           age  quantity    price
count 99457.00  99457.00 99457.00
mean     43.43      3.00   689.26
std      14.99      1.41   941.18
min      18.00      1.00     5.23
25%      30.00      2.00    45.45
50%      43.00      3.00   203.30
75%      56.00      4.00  1200.32
max      69.00      5.00  5250.00

In [12]:
df.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [21]:
#value counts for each categoric columns
dfc = ['gender', 'category', 'payment_method', 'shopping_mall']
for col in dfc:
    print(f"Value counts for column '{col}':")
    print(df[col].value_counts())
    print("\n")

Value counts for column 'gender':
gender
Female    59482
Male      39975
Name: count, dtype: int64


Value counts for column 'category':
category
Clothing           34487
Cosmetics          15097
Food & Beverage    14776
Toys               10087
Shoes              10034
Souvenir            4999
Technology          4996
Books               4981
Name: count, dtype: int64


Value counts for column 'payment_method':
payment_method
Cash           44447
Credit Card    34931
Debit Card     20079
Name: count, dtype: int64


Value counts for column 'shopping_mall':
shopping_mall
Mall of Istanbul     19943
Kanyon               19823
Metrocity            15011
Metropol AVM         10161
Istinye Park          9781
Zorlu Center          5075
Cevahir AVM           4991
Forum Istanbul        4947
Viaport Outlet        4914
Emaar Square Mall     4811
Name: count, dtype: int64

In [17]:
df['invoice_date'] = pd.to_datetime(df['invoice_date'], format='mixed')

In [30]:
df['invoice_month'] = df['invoice_date'].dt.month
df['invoice_year'] = df['invoice_date'].dt.year

In [41]:
df['revenue'] = df['price'] * df['quantity']

In [42]:
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,invoice_month,invoice_year,revenue
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-05-08,Kanyon,5,2022,7502.00
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,12,2021,5401.53
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-09-11,Metrocity,9,2021,300.08
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,5,2021,15004.25
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,10,2021,242.40

In [40]:
selc = ['category', 'payment_method', 'shopping_mall', 'gender']

for col in selc:
    print(f"Average price for  {col}:")
    print(df.groupby(col)['price'].mean().sort_values(ascending=False))
    print("\n")

Average price for  category:
category
Technology        3156.94
Shoes             1807.39
Clothing           901.08
Cosmetics          122.45
Toys               107.73
Books               45.57
Souvenir            34.89
Food & Beverage     15.67
Name: price, dtype: float64


Average price for  payment_method:
payment_method
Cash          690.82
Credit Card   688.54
Debit Card    687.03
Name: price, dtype: float64


Average price for  shopping_mall:
shopping_mall
Emaar Square Mall   704.72
Viaport Outlet      694.75
Mall of Istanbul    694.57
Kanyon              691.66
Zorlu Center        691.56
Cevahir AVM         687.97
Istinye Park        686.75
Metrocity           682.83
Metropol AVM        682.81
Forum Istanbul      674.36
Name: price, dtype: float64


Average price for  gender:
gender
Male     690.92
Female   688.14
Name: price, dtype: float64